export const ErrorCodes = {
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  INVALID_CURSOR: "INVALID_CURSOR",
  CONFIG_INVALID: "CONFIG_INVALID",
  CONFIG_VERSION_UNSUPPORTED: "CONFIG_VERSION_UNSUPPORTED",
  RESOURCE_LIMIT: "RESOURCE_LIMIT",
  HOST_NOT_REGISTERED: "HOST_NOT_REGISTERED",
  HOST_KEY_REJECTED: "HOST_KEY_REJECTED",
  HOST_KEY_CHANGED: "HOST_KEY_CHANGED",
  CONNECTION_REFUSED: "CONNECTION_REFUSED",
  CONNECTION_TIMEOUT: "CONNECTION_TIMEOUT",
  PLATFORM_MISMATCH: "PLATFORM_MISMATCH",
  AUTH_UNAVAILABLE: "AUTH_UNAVAILABLE",
  AUTH_FAILED: "AUTH_FAILED",
  INTERACTIVE_AUTH_UNSUPPORTED: "INTERACTIVE_AUTH_UNSUPPORTED",
  APPROVAL_UNSUPPORTED: "APPROVAL_UNSUPPORTED",
  APPROVAL_DECLINED: "APPROVAL_DECLINED",
  APPROVAL_TIMEOUT: "APPROVAL_TIMEOUT",
  APPROVAL_INTENT_MISMATCH: "APPROVAL_INTENT_MISMATCH",
  POLICY_NOT_FOUND: "POLICY_NOT_FOUND",
  POLICY_DENIED: "POLICY_DENIED",
  POLICY_REQUIRES_APPROVAL: "POLICY_REQUIRES_APPROVAL",
  COMMAND_FAILED: "COMMAND_FAILED",
  COMMAND_TIMEOUT: "COMMAND_TIMEOUT",
  OUTPUT_TRUNCATED: "OUTPUT_TRUNCATED",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  SESSION_NOT_ACTIVE: "SESSION_NOT_ACTIVE",
  SESSION_DISCONNECTED: "SESSION_DISCONNECTED",
  PATH_DENIED: "PATH_DENIED",
  LINK_NOT_ALLOWED: "LINK_NOT_ALLOWED",
  TARGET_EXISTS: "TARGET_EXISTS",
  ATOMIC_REPLACE_UNSUPPORTED: "ATOMIC_REPLACE_UNSUPPORTED",
  TRANSFER_FAILED: "TRANSFER_FAILED",
  TRANSFER_TIMEOUT: "TRANSFER_TIMEOUT",
  PARTIAL_FAILURE: "PARTIAL_FAILURE",
  OPERATION_NOT_FOUND: "OPERATION_NOT_FOUND",
  OPERATION_EXPIRED: "OPERATION_EXPIRED",
  CANCEL_UNCONFIRMED: "CANCEL_UNCONFIRMED",
  STATE_UNKNOWN: "STATE_UNKNOWN",
  TRUST_STORE_ERROR: "TRUST_STORE_ERROR",
  CONSOLE_LISTEN_DENIED: "CONSOLE_LISTEN_DENIED",
  CONSOLE_START_FAILED: "CONSOLE_START_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

const errorCodeValues = new Set<unknown>(Object.values(ErrorCodes));

export function isErrorCode(value: unknown): value is ErrorCode {
  return errorCodeValues.has(value);
}
